site_name: My Docs

site_url: https://sitename.example
theme:
  name: material
nav:
  - Documentation: index.md
  - Home: body.md
  - Player: player.md
  - Enemy: enemy.md
  - Game Controler: game-controls.md
  - TileMap: tilemaps-levels.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md
  - Optional Enemy: enemy-higher-level.md

  