site_name: My Docs

site_url: https://sitename.example
theme:
  name: material
  features:
    - content.code.copy
nav:
  - Home: intro.md
  - Installation: body.md
  - Player: player.md
  - Enemy: enemy.md
  - Game Controler: game-controls.md
  - TileMap: tilemaps-levels.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md
  - Optional Enemy: enemy-higher-level.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  